USE sistinf;
GO

CREATE TABLE CARGO (
ID_CARGO INT PRIMARY KEY NOT NULL,
CARGO VARCHAR(50),
DESCRIPCION VARCHAR(255)
);


CREATE TABLE USUARIO (
ID_USUARIO INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
CORREO VARCHAR(50),
CONTRASENA VARCHAR(100),
ID_CARGO INT FOREIGN KEY REFERENCES CARGO (ID_CARGO)
);

CREATE TABLE TIPO_DE_PLAN (
ID_TIPO_DE_PLAN INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
DESCRIPCION VARCHAR(255)
);


CREATE TABLE PLAN_EO (
ID_PLAN INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
FECHA DATE,
ID_TIPO_DE_PLAN INT FOREIGN KEY REFERENCES TIPO_DE_PLAN (ID_TIPO_DE_PLAN),
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO)
);



CREATE TABLE USUARIO_PLAN_EO (
ID_PLAN INT FOREIGN KEY REFERENCES PLAN_EO (ID_PLAN) NOT NULL,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO)NOT NULL,
PRIMARY KEY CLUSTERED (ID_PLAN, ID_USUARIO),
);

CREATE TABLE IMPERATIVO (
ID_IMPERATIVO INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
FECHA_INICIO DATE,
FECHA_FIN DATE,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO),
);


CREATE TABLE USUARIO_IMPERATIVO (
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO) NOT NULL,
ID_IMPERATIVO INT FOREIGN KEY REFERENCES IMPERATIVO (ID_IMPERATIVO) NOT NULL,
PRIMARY KEY CLUSTERED (ID_USUARIO, ID_IMPERATIVO ),
);


CREATE TABLE OBJETIVO (
ID_OBJETIVO INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
COMPLETUD_POR VARCHAR(255),
ID_IMPERATIVO INT FOREIGN KEY REFERENCES IMPERATIVO (ID_IMPERATIVO)
);


CREATE TABLE EVALUACION (
ID_EVALUACION INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
DESCRIPCION VARCHAR(255),
RANGO INT,
ID_CARGO INT FOREIGN KEY REFERENCES CARGO (ID_CARGO)
);

CREATE TABLE EVOLUCION (
ID_EVOLUCION INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
DESCRIPCION VARCHAR(255),
ID_PLAN INT FOREIGN KEY REFERENCES PLAN_EO (ID_PLAN)
);


CREATE TABLE ACCION (
ID_ACCION INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
DESCRIPCION VARCHAR(255)
);


CREATE TABLE ACTIVIDAD_CLAVE (
ID_ACTIVIDAD INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
DESCRIPCION VARCHAR(255),
FECHA_FIN DATE,
ID_EVALUACION INT FOREIGN KEY REFERENCES EVALUACION (ID_EVALUACION),
ID_OBJETIVO INT FOREIGN KEY REFERENCES OBJETIVO (ID_OBJETIVO),
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO),
ID_PLAN INT FOREIGN KEY REFERENCES PLAN_EO (ID_PLAN),
ID_ACCION INT FOREIGN KEY REFERENCES ACCION (ID_ACCION)
);


CREATE TABLE REPORTE (
ID_REPORTE INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
LINK VARCHAR(255),
ID_PLAN INT FOREIGN KEY REFERENCES PLAN_EO (ID_PLAN),
ID_EVALUACION INT FOREIGN KEY REFERENCES EVALUACION (ID_EVALUACION),
ID_ACTIVIDAD INT FOREIGN KEY REFERENCES ACTIVIDAD_CLAVE (ID_ACTIVIDAD)
);



------------------------------- VALORES
INSERT INTO CARGO (ID_CARGO, CARGO, DESCRIPCION)
VALUES
(1, 'ADMINISTRADOR', 'CRUD en cualquier lugar de la plataforma'),
(2, 'PLANEADOR', 'CRUD de planes estrategicos y operativos, puede evaluar acciones'),
(3, 'LIDER IMPERATIVO', 'Permisos sobre el imperativo que pertenezca, craer acciones y evaluarlas'),
(4, 'EJECUTOR', 'Crea acciones y evaluarlas');


INSERT INTO USUARIO (ID_USUARIO, NOMBRE, CORREO, CONTRASENA, ID_CARGO)
VALUES 
(1, 'Nicole Continelli', 'nicolecofl@unisabana.edu.co', 'Alessandro', 1),
(2, 'Luis Martinez', 'luismacr@unisabana.edu.co', 'Luised00', 1),
(3, 'Hugo Cordoba', 'hugocor@gmail.com', 'HugoCordProf', 1);

INSERT INTO TIPO_DE_PLAN (ID_TIPO_DE_PLAN, NOMBRE, DESCRIPCION)
VALUES 
(1, 'Plan Estrategico', 'Todos pueden ver la estructura. El planeador crear imperativos, objetivos y actividades clave y los ejecutores crean acciones y se evaluan'),
(2, 'Plan Operativo', 'Exclusiva por cargo. Los ejecutores solo pueden ver la estructura de cargo, accion y operacion. El planeador puede ver todas las acciones de todos los cargos');
